DROP TRIGGER IF EXISTS trg_reminder_tombstone ON contacts.reminders;
DROP FUNCTION IF EXISTS contacts.reminder_tombstone();
DROP TABLE IF EXISTS contacts.reminder_tombstones;
DROP TRIGGER IF EXISTS trg_reminder_change_seq ON contacts.reminders;
DROP FUNCTION IF EXISTS contacts.bump_reminder_change_seq();
ALTER TABLE contacts.reminders DROP COLUMN IF EXISTS change_seq;
DROP SEQUENCE IF EXISTS contacts.reminder_change_seq;
DROP TRIGGER IF EXISTS trg_gm_bump_group ON contacts.group_members;
DROP FUNCTION IF EXISTS contacts.gm_bump_group();
DROP TRIGGER IF EXISTS trg_group_tombstone ON contacts.groups;
DROP FUNCTION IF EXISTS contacts.group_tombstone();
DROP TABLE IF EXISTS contacts.group_tombstones;
DROP TRIGGER IF EXISTS trg_group_change_seq ON contacts.groups;
DROP FUNCTION IF EXISTS contacts.bump_group_change_seq();
ALTER TABLE contacts.groups DROP COLUMN IF EXISTS change_seq;
DROP SEQUENCE IF EXISTS contacts.group_change_seq;
DROP TRIGGER IF EXISTS trg_cl_bump_contact ON contacts.contact_labels;
DROP FUNCTION IF EXISTS contacts.cl_bump_contact();
DROP TRIGGER IF EXISTS trg_label_tombstone ON contacts.labels;
DROP FUNCTION IF EXISTS contacts.label_tombstone();
DROP TABLE IF EXISTS contacts.label_tombstones;
DROP TRIGGER IF EXISTS trg_label_change_seq ON contacts.labels;
DROP FUNCTION IF EXISTS contacts.bump_label_change_seq();
ALTER TABLE contacts.labels DROP COLUMN IF EXISTS change_seq;
DROP SEQUENCE IF EXISTS contacts.label_change_seq;
DROP TRIGGER IF EXISTS trg_contact_tombstone ON contacts.contacts;
DROP FUNCTION IF EXISTS contacts.contact_tombstone();
DROP TABLE IF EXISTS contacts.contact_tombstones;
DROP TRIGGER IF EXISTS trg_contact_change_seq ON contacts.contacts;
DROP FUNCTION IF EXISTS contacts.bump_contact_change_seq();
ALTER TABLE contacts.contacts DROP COLUMN IF EXISTS change_seq;
DROP SEQUENCE IF EXISTS contacts.contact_change_seq;
